CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    genre VARCHAR(80) NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    credits DECIMAL(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cart_items (
    client_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    PRIMARY KEY (client_id, game_id),
    CONSTRAINT fk_cart_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_cart_game FOREIGN KEY (game_id) REFERENCES games(id)
);

CREATE TABLE IF NOT EXISTS wishlist_items (
    client_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    PRIMARY KEY (client_id, game_id),
    CONSTRAINT fk_wishlist_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_wishlist_game FOREIGN KEY (game_id) REFERENCES games(id)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    total DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    game_title VARCHAR(150) NOT NULL,
    game_genre VARCHAR(80) NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    quantity INT NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE IF NOT EXISTS coupons (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)   NOT NULL UNIQUE,
    discount_pct DECIMAL(5,2)  NOT NULL,
    active       BOOLEAN       NOT NULL DEFAULT TRUE
);

