CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    genre VARCHAR(80) NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    credits DECIMAL(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cart_items (
    client_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    PRIMARY KEY (client_id, game_id),
    CONSTRAINT fk_cart_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_cart_game FOREIGN KEY (game_id) REFERENCES games(id)
);

